export const metadata = {
  title: 'VTube Center',
  description: 'Get a list of every anime Virtual Doggirl in the world!',
  keywords: [
    'virtual',
    'doggirls',
    'dog',
    'girls',
    'anime',
    'list',
    'online',
    'media',
    'link',
    'video',
    'image',
    'live',
    'stream',
    'livestream',
  ],
  google: 'notranslate',
  rating: 'general',
  googleSiteVerification: 'u_JknkJF5JDYvj-PzNGwOc2XQ0XRfryIgr8PeF0y3Vc',
  openGraph: {
    type: 'website',
    locale: 'en-US',
    title: 'VTube Center',
    description: 'Get a list of every anime Virtual Doggirl in the world!',
  },
  twitter: {
    images:
      'https://github.com/136MasterNR/VTubeCenter/raw/migration/app/public/img/seo/embed.jpg',
    title: 'VTube Center',
    card: 'summary_large_image',
    creator: '@136MasterNR and @Naibuu',
  },
}